import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e5e1e4',
        'outline': '#7f7663',
        'on-tertiary-fixed': '#002117',
        'on-error': '#ffffff',
        'on-surface': '#1c1b1d',
        'on-surface-variant': '#4d4635',
        'primary-fixed-dim': '#e9c34a',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#141a32',
        'on-primary-fixed-variant': '#574500',
        'tertiary': '#376757',
        'on-secondary-fixed-variant': '#404560',
        'on-primary-container': '#745c00',
        'on-secondary-container': '#5c617d',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f3f0f3',
        'tertiary-fixed': '#baeed9',
        'surface-tint': '#735c00',
        'primary': '#735c00',
        'tertiary-fixed-dim': '#9ed1bd',
        'tertiary-container': '#b1e5d0',
        'surface': '#fcf8fb',
        'surface-container-high': '#ebe7ea',
        'inverse-surface': '#313032',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#241a00',
        'secondary-fixed': '#dde1ff',
        'outline-variant': '#d0c6af',
        'surface-container-highest': '#e5e1e4',
        'background': '#fcf8fb',
        'secondary': '#575d79',
        'surface-container-low': '#f6f2f5',
        'on-secondary': '#ffffff',
        'inverse-primary': '#e9c34a',
        'primary-fixed': '#ffe088',
        'secondary-fixed-dim': '#c0c5e5',
        'error': '#ba1a1a',
        'on-background': '#1c1b1d',
        'surface-container': '#f1edf0',
        'surface-dim': '#dcd9dc',
        'on-tertiary-fixed-variant': '#1d4f40',
        'primary-container': '#fed65b',
        'secondary-container': '#d9deff',
        'surface-bright': '#fcf8fb',
        'on-tertiary-container': '#386858',
        'on-primary': '#ffffff',
        farva: {
          navy: {
            royal: '#141A32',
            deep: '#0A1128',
            surface: '#1E2646',
            card: '#18203D',
          },
          gold: {
            sahara: '#FED65B',
            hover: '#E5BF42',
            light: '#FFEAA7',
          },
          porcelain: '#FCF8FB',
          slate: {
            100: '#F1F5F9',
            300: '#CBD5E1',
            400: '#94A3B8',
            700: '#334155',
            800: '#1E293B',
          }
        },
        brand: {
          primary: '#FED65B',
          'primary-hover': '#E5BF42',
          secondary: '#141A32',
          dark: '#0A1128',
          light: '#FCF8FB',
          gold: '#FED65B',
        },
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      spacing: {
        'margin-desktop': '4rem',
        'space-xs': '0.25rem',
        'margin': '1.25rem',
        'space-lg': '1.75rem',
        'gutter-desktop': '2.5rem',
        'space-xl': '3rem',
        'gutter': '1.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem'
      },
      fontFamily: {
        'coordinate-meta': ['Space Mono', 'monospace'],
        'display-hero-mobile': ['Bodoni Moda', 'serif'],
        'display-hero': ['Bodoni Moda', 'serif'],
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'telemetry-data': ['Space Mono', 'monospace'],
        'body-sm': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Bodoni Moda', 'serif'],
        'headline-md': ['Bodoni Moda', 'serif'],
        'headline-lg': ['Bodoni Moda', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        heading: ['Outfit', 'Inter', 'sans-serif'],
        body: ['Hanken Grotesk', 'Inter', 'sans-serif'],
        gujarati: ['Noto Sans Gujarati', 'sans-serif'],
      },
      fontSize: {
        'coordinate-meta': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '400' }],
        'display-hero-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-hero': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '0.01em', fontWeight: '600' }],
        'telemetry-data': ['13px', { lineHeight: '18px', letterSpacing: '0.04em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '0em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '700' }]
      },
      boxShadow: {
        'farva-gold': '0 0 25px -5px rgba(254, 214, 91, 0.3)',
        'farva-card': '0 10px 30px -10px rgba(10, 17, 40, 0.5)',
      }
    },
  },
  plugins: [],
};
export default config;

