global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chalo_farva_backend'
    metrics_path: '/api/v1/health'
    static_configs:
      - targets: ['backend:4000']

  - job_name: 'chalo_farva_ai'
    metrics_path: '/health'
    static_configs:
      - targets: ['ai_service:8000']
